[package]
authors = ["Jake O`Shannessy <joshannessy@affinity-fire.com>"]
edition = "2018"
name = "data-vector"
version = "0.1.6"

[dependencies]
chrono = {version = "0.4", default-features = false}
serde = {version = "1", features = ["derive"]}
