[package]
name = "data-vector"
version = "0.1.4"
authors = ["Jake O`Shannessy <joshannessy@affinity-eng.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
